### ISSUE TITLE
LoadCustomerInfo doesn't work

### ISSUE THREAD

**Issue by stories2** [djangoServer/djangoServer#24]
## Problem File Name
CustomerInfoDatabase.py
## Expected behavior
`{Result:Fail}`
## Actual behavior
`Internal Server Error: /Smoothie/2/LoadCustomerInfo/`
## Steps to reproduce the behavior
It always happen.
Call this
`http://stories3.iptime.org:4200/Smoothie/2/LoadCustomerInfo/`
## Program printed log
```
[02/Apr/2017 08:26:49] "GET /Smoothie/2/LoadAllStoreInfo/ HTTP/1.1" 200 822
insert into `회원정보` (`전화번호`, `이름`, `생일`, `이메일`) select * from (select 'N/A' as `전화번호` , 'customer' as `이름` , '0000-00-00' as `생일` , 'stories282@gmail.com' as `이메일` ) as compareTemp where not exists (select `전화번호` , `이름` , `생일` , `이메일`  from `회원정보` where `이메일` = 'stories282@gmail.com') limit 1;
[02/Apr/2017 08:26:49] "GET /Smoothie/2/InsertNewCustomerInfo/?name=customer&phone=N/A&email=stories282@gmail.com&birthday=0000-00-00 HTTP/1.1" 200 16
SELECT * FROM `회원정보` WHERE `이메일` = 'stories282@gmail.com';
Internal Server Error: /Smoothie/2/LoadCustomerInfo/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stories2/djangoServer/webService/BackEnd/Database/CustomerInfoDatabase.py", line 68, in LoadCustomerInfo
    return HttpResponse(json.dumps(customerInfoData, ensure_ascii=False), content_type="application/json")
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 3, 19, 15, 6, 56) is not JSON serializable
[02/Apr/2017 08:26:50] "GET /Smoothie/2/LoadCustomerInfo/?email=stories282@gmail.com HTTP/1.1" 500 87563
```

**Comment by stories2** [comment]
Fixed
93df857cf0c4f2f85e02e1a0c69861c72b9de021

**Comment by stories2** [comment]
Error reopen. 
Same problem.
067feabdabdbf34d748250798800704d6003ca44

**Comment by stories2** [comment]
00f0acf
Error found. 
```
+--------------------------------+--------------+------+-----+----------------------+----------------+
| Field                          | Type         | Null | Key | Default              | Extra          |
+--------------------------------+--------------+------+-----+----------------------+----------------+
| 회원번호                       | int(11)      | NO   | PRI | NULL                 | auto_increment |
| 이름                           | varchar(45)  | YES  |     | NULL                 |                |
| 전화번호                       | varchar(20)  | YES  |     | NULL                 |                |
| 이메일                         | varchar(100) | YES  |     | NULL                 |                |
| 생일                           | date         | YES  |     | NULL                 |                |
| 국가코드                       | varchar(10)  | YES  |     | NULL                 |                |
| 회원 이미지 저장 경로          | varchar(200) | YES  |     | NULL                 |                |
| 회원 등급                      | int(11)      | YES  |     | 1                    |                |
| 정보 변경 날짜                 | timestamp(6) | YES  |     | CURRENT_TIMESTAMP(6) |                |
| 안드로이드SDK레벨              | int(11)      | YES  |     | 1                    |                |
| 핸드폰기종                     | varchar(200) | YES  |     | NULL                 |                |
| 회원비활성화                   | tinyint(1)   | YES  |     | 0                    |                |
| 회원 등록일                    | timestamp    | NO   |     | CURRENT_TIMESTAMP    |                |
+--------------------------------+--------------+------+-----+----------------------+----------------+
13 rows in set (0.01 sec)
```
This table don't have `회원 등록일`;
